package com.chat.im.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.chat.im.db.bean.ContactInfo;
import com.chat.im.db.bean.message.MessageBase;
import com.chat.im.db.bean.MessagePreView;
import com.chat.im.db.bean.WaitAddFriends;

import com.chat.im.db.dao.ContactInfoDao;
import com.chat.im.db.dao.MessageBaseDao;
import com.chat.im.db.dao.MessagePreViewDao;
import com.chat.im.db.dao.WaitAddFriendsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactInfoDaoConfig;
    private final DaoConfig messageBaseDaoConfig;
    private final DaoConfig messagePreViewDaoConfig;
    private final DaoConfig waitAddFriendsDaoConfig;

    private final ContactInfoDao contactInfoDao;
    private final MessageBaseDao messageBaseDao;
    private final MessagePreViewDao messagePreViewDao;
    private final WaitAddFriendsDao waitAddFriendsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactInfoDaoConfig = daoConfigMap.get(ContactInfoDao.class).clone();
        contactInfoDaoConfig.initIdentityScope(type);

        messageBaseDaoConfig = daoConfigMap.get(MessageBaseDao.class).clone();
        messageBaseDaoConfig.initIdentityScope(type);

        messagePreViewDaoConfig = daoConfigMap.get(MessagePreViewDao.class).clone();
        messagePreViewDaoConfig.initIdentityScope(type);

        waitAddFriendsDaoConfig = daoConfigMap.get(WaitAddFriendsDao.class).clone();
        waitAddFriendsDaoConfig.initIdentityScope(type);

        contactInfoDao = new ContactInfoDao(contactInfoDaoConfig, this);
        messageBaseDao = new MessageBaseDao(messageBaseDaoConfig, this);
        messagePreViewDao = new MessagePreViewDao(messagePreViewDaoConfig, this);
        waitAddFriendsDao = new WaitAddFriendsDao(waitAddFriendsDaoConfig, this);

        registerDao(ContactInfo.class, contactInfoDao);
        registerDao(MessageBase.class, messageBaseDao);
        registerDao(MessagePreView.class, messagePreViewDao);
        registerDao(WaitAddFriends.class, waitAddFriendsDao);
    }
    
    public void clear() {
        contactInfoDaoConfig.clearIdentityScope();
        messageBaseDaoConfig.clearIdentityScope();
        messagePreViewDaoConfig.clearIdentityScope();
        waitAddFriendsDaoConfig.clearIdentityScope();
    }

    public ContactInfoDao getContactInfoDao() {
        return contactInfoDao;
    }

    public MessageBaseDao getMessageBaseDao() {
        return messageBaseDao;
    }

    public MessagePreViewDao getMessagePreViewDao() {
        return messagePreViewDao;
    }

    public WaitAddFriendsDao getWaitAddFriendsDao() {
        return waitAddFriendsDao;
    }

}
