package com.chat.im.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.chat.im.db.bean.ContactInfo;
import com.chat.im.db.bean.MessagePreView;

import com.chat.im.db.dao.ContactInfoDao;
import com.chat.im.db.dao.MessagePreViewDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactInfoDaoConfig;
    private final DaoConfig messagePreViewDaoConfig;

    private final ContactInfoDao contactInfoDao;
    private final MessagePreViewDao messagePreViewDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactInfoDaoConfig = daoConfigMap.get(ContactInfoDao.class).clone();
        contactInfoDaoConfig.initIdentityScope(type);

        messagePreViewDaoConfig = daoConfigMap.get(MessagePreViewDao.class).clone();
        messagePreViewDaoConfig.initIdentityScope(type);

        contactInfoDao = new ContactInfoDao(contactInfoDaoConfig, this);
        messagePreViewDao = new MessagePreViewDao(messagePreViewDaoConfig, this);

        registerDao(ContactInfo.class, contactInfoDao);
        registerDao(MessagePreView.class, messagePreViewDao);
    }
    
    public void clear() {
        contactInfoDaoConfig.clearIdentityScope();
        messagePreViewDaoConfig.clearIdentityScope();
    }

    public ContactInfoDao getContactInfoDao() {
        return contactInfoDao;
    }

    public MessagePreViewDao getMessagePreViewDao() {
        return messagePreViewDao;
    }

}
