package com.chat.im.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.chat.im.db.bean.WaitAddFriends;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WAIT_ADD_FRIENDS".
*/
public class WaitAddFriendsDao extends AbstractDao<WaitAddFriends, Void> {

    public static final String TABLENAME = "WAIT_ADD_FRIENDS";

    /**
     * Properties of entity WaitAddFriends.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property AddFriendAttachMessage = new Property(0, String.class, "addFriendAttachMessage", false, "ADD_FRIEND_ATTACH_MESSAGE");
    }


    public WaitAddFriendsDao(DaoConfig config) {
        super(config);
    }
    
    public WaitAddFriendsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WAIT_ADD_FRIENDS\" (" + //
                "\"ADD_FRIEND_ATTACH_MESSAGE\" TEXT);"); // 0: addFriendAttachMessage
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WAIT_ADD_FRIENDS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WaitAddFriends entity) {
        stmt.clearBindings();
 
        String addFriendAttachMessage = entity.getAddFriendAttachMessage();
        if (addFriendAttachMessage != null) {
            stmt.bindString(1, addFriendAttachMessage);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WaitAddFriends entity) {
        stmt.clearBindings();
 
        String addFriendAttachMessage = entity.getAddFriendAttachMessage();
        if (addFriendAttachMessage != null) {
            stmt.bindString(1, addFriendAttachMessage);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public WaitAddFriends readEntity(Cursor cursor, int offset) {
        WaitAddFriends entity = new WaitAddFriends( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // addFriendAttachMessage
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WaitAddFriends entity, int offset) {
        entity.setAddFriendAttachMessage(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(WaitAddFriends entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(WaitAddFriends entity) {
        return null;
    }

    @Override
    public boolean hasKey(WaitAddFriends entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
